DATA:
  data_root: dataset/IQON3000
  train_data_ori: dataset/IQON3000/data/train.csv
  valid_data_ori: dataset/IQON3000/data/valid.csv
  test_data_ori: dataset/IQON3000/data/test.csv
  visual_features_dict_ori: dataset/IQON3000/feat/visualfeatures
  textural_idx_dict_ori: dataset/IQON3000/feat/textfeatures
  textural_embedding_matrix: dataset/IQON3000/feat/smallnwjc2vec
  user_map: dataset/IQON3000/data/user_map.json
  item_map: dataset/IQON3000/data/item_map.json
  visual_features_tensor: dataset/IQON3000/feat/visualfeatures_indexedtenseor
  textural_features_tensor: dataset/IQON3000/feat/textfeatures_indexedtenseor
  train_data: dataset/IQON3000/data/train_indexed.csv
  valid_data: dataset/IQON3000/data/valid_indexed.csv
  test_data: dataset/IQON3000/data/test_indexed.csv

TRAIN:
  arch: NiPCBPR
  dataset: IQON3000
  epochs: 80
  start_epoch: 0
  max_sentence: 83
  print_freq: 1
  workers: 2
  batch_size: 1024
  hidden_dim: 512
  text_feature_dim: 300
  visual_feature_dim: 2048
  textcnn_layer: 4
  with_visual: True
  with_text: True
  train_gpu: [0]
  base_lr: 0.001 # learning rate
  wd: 0.00001 # weight decay
  num_interaction: 2 # choose 2 bottoms that has been chose by the given top
  patience: 5 # for early stop
  with_Nor: True # Feature Scaling
  b_PC: True # project bottom into personalization and conpatibility spaces separately
  UC: False # user preference consistency branch
  IC: False # item compatibility consistency branch
  iPC: True # indirect personal compatibility branch
  cos: True # using cosine similairity calculate distance
  weight:  # path to initial weight (default: none)
  resume:  # 
  UC_w: 4
  IC_w: 4
  weight_P: 0.3
  iPC_w: 3
  his_select_t: False # using textual information to help to select historical bottoms
  popular_padding: True # using popular items to padding those historiacl interactions less than default number
  repeated_interact: False # only contain one interaction for those bottoms chosed by same top/user more than twice for history selection
  save_path: saved/IQON3000/NiPCBPR
  evaluate: True
  batch_size_val: 1024
  start_epoch: 0
  num_his: 2
  num_interact: 2
  iPC_v_w: 0.5
  save_freq: 1

Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_batch_size: 1024
  test_gpu: [0]
  has_prediction: False # has prediction already or not
  model_path: saved/IQON3000/NiPCBPR/train_epoch_13.pth     # evaluation model path
  save_folder: saved/Polyvore_519/NiPCBPR/result/   #test results save folder
  test_distributed: False